# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.cache/wt} [current_project]
set_property parent.project_path {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {g:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/imports/AC/LAB3/LAB3.srcs/sources_1/new/BLOC_REG.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/new/EX.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/new/ID.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/new/MEM.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/imports/AC/SDD + MPG/SDD + MPG.srcs/sources_1/new/MPG.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/imports/AC/SDD + MPG/SDD + MPG.srcs/sources_1/new/SSD.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/new/UC.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/imports/AC/LAB4/LAB4.srcs/sources_1/new/Unitate_IF.vhd}
  {G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/sources_1/new/test_env.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/constrs_1/new/Constraints.xdc}}
set_property used_in_implementation false [get_files {{G:/Laptop/Facultate/An 2 Semestrul 2/Facultate Eu/AC/MIPS16/MIPS16.srcs/constrs_1/new/Constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TestInstructionDecode -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TestInstructionDecode.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TestInstructionDecode_utilization_synth.rpt -pb TestInstructionDecode_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
